FROM debian
RUN apt update && apt install -y wget tar bzip2
RUN wget http://dl.4players.de/ts/releases/3.0.13.8/teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2
RUN tar -xf teamspeak3-server_linux_amd64-3.0.13.8.tar.bz2

